// Package runtime provides the GoWave HTTP server used inside user apps.
// It handles SSR rendering, WASM bundle serving, and action dispatch.
package runtime

import (
	"fmt"
	"net/http"
)

// Config controls the runtime server.
type Config struct {
	Port    string
	RootDir string
}

// Server is the GoWave application server.
type Server struct {
	cfg Config
	mux *http.ServeMux
}

// NewServer creates a Server with the given config.
func NewServer(cfg Config) *Server {
	s := &Server{cfg: cfg, mux: http.NewServeMux()}
	s.registerRoutes()
	return s
}

// ListenAndServe starts the HTTP server.
func (s *Server) ListenAndServe() error {
	addr := ":" + s.cfg.Port
	fmt.Printf("gowave runtime → http://localhost%s\n", addr)
	return http.ListenAndServe(addr, s.mux)
}

func (s *Server) registerRoutes() {
	// WASM bundle
	s.mux.HandleFunc("/_wasm/", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, s.cfg.RootDir+"/dist/main.wasm")
	})

	// Action dispatcher — POST /_action/{id}
	s.mux.HandleFunc("/_action/", s.handleAction)

	// Public assets
	s.mux.Handle("/", http.FileServer(http.Dir(s.cfg.RootDir+"/dist")))
}

// handleAction receives server action calls from the WASM client.
// The client POSTs JSON state, the server runs the action method,
// and responds with a JSON patch of changed fields.
func (s *Server) handleAction(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	// Action routing will be code-generated by the CLI.
	// For now, return a stub response.
	w.Header().Set("Content-Type", "application/json")
	fmt.Fprint(w, `{"patches":[]}`)
}
