// Package scaffold generates a new GoWave project from embedded templates.
package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// Options controls what gowave new creates.
type Options struct {
    Name         string // project name, used in titles
    Dir          string // output directory
    Module       string // Go module path for the new project
    GowavePath   string // local path to the gowave framework source
    GowaveModule string // Go module name of the gowave framework
}
// Run scaffolds a full GoWave project into opts.Dir.
func Run(opts Options) error {
	if _, err := os.Stat(opts.Dir); err == nil {
		return fmt.Errorf("directory %q already exists", opts.Dir)
	}

	fmt.Printf("  creating %s/\n", opts.Dir)

	files := buildFileMap(opts)
	for path, content := range files {
		full := filepath.Join(opts.Dir, path)
		if err := writeFile(full, content, opts); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
		fmt.Printf("  + %s\n", path)
	}

	fmt.Printf("\nDone! Next steps:\n")
	fmt.Printf("  cd %s\n", opts.Dir)
	fmt.Printf("  gowave dev\n\n")
	return nil
}

func buildFileMap(opts Options) map[string]string {
	return map[string]string{
		"gowave.toml":               tmplGowaveToml,
		"go.mod":                    tmplGoMod,
		"go.sum":                    "",
		"main.go":                   tmplMainGo,
		"layout.go":                 tmplLayoutGo,
		"pages/index.go":            tmplIndexPage,
		"components/.keep":          "",
		"store/.keep":               "",
		"db/.keep":                  "",
		"middleware/.keep":           "",
		"public/favicon.ico":        "",
		"public/gowave.js":          tmplGowaveJS,
		".gitignore":                tmplGitignore,
		"README.md":                 tmplReadme,
	}
}

func writeFile(path, content string, opts Options) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	rendered, err := renderTemplate(content, opts)
	if err != nil {
		return err
	}
	return os.WriteFile(path, []byte(rendered), 0644)
}

func renderTemplate(tmpl string, opts Options) (string, error) {
	if tmpl == "" {
		return "", nil
	}
	t, err := template.New("").Parse(tmpl)
	if err != nil {
		return "", err
	}
	var sb strings.Builder
	if err := t.Execute(&sb, opts); err != nil {
		return "", err
	}
	return sb.String(), nil
}

// ── Templates ────────────────────────────────────────────────────────────────

const tmplGowaveToml = `# GoWave project configuration
module = "{{.Module}}"
name   = "{{.Name}}"
port   = "3000"
target = "go"      # WASM compilation target (standard Go)
out    = "dist/"

[build]
  split_routes = true   # per-route WASM chunks
  minify       = false
`

const tmplGoMod = `module {{.Module}}

go 1.22

require (
	github.com/gowave/gowave v0.1.0
)
{{- if .GowavePath}}

replace github.com/gowave/gowave => {{.GowavePath}}
{{- end}}
`

const tmplMainGo = `package main

import (
	"fmt"
	"net/http"
	"os"
)

func main() {
	port := "3000"
	if p := os.Getenv("PORT"); p != "" {
		port = p
	}
	fmt.Printf("gowave app → http://localhost:%s\n", port)
	if err := http.ListenAndServe(":"+port, nil); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
`

const tmplLayoutGo = `package main

// RootLayout wraps every page. Implement Render(slot) once GoWave is published.
// For now the dev server uses its own default shell.
//
// When gowave is available as a module:
//
//	import "github.com/gowave/gowave/pkg/ui"
//
//	func (l *RootLayout) Render(slot ui.Node) ui.Node {
//	    return ui.Html(
//	        ui.Head(ui.Child(ui.Title("{{.Name}}"))),
//	        ui.Body(ui.Child(slot)),
//	    )
//	}
type RootLayout struct{}
`

const tmplIndexPage = `package pages

// +gowave:page route="/"
// IndexPage is the root page of your GoWave app.
// Uncomment the Render method once github.com/gowave/gowave is available
// (or set a replace directive in go.mod pointing to your local gowave source).
type IndexPage struct {
	Count int
}

// func (p *IndexPage) Render() ui.Node {
// 	return ui.Div(ui.Class("container"),
// 		ui.H1(ui.Text("Hello from GoWave")),
// 		ui.Button(
// 			ui.OnClick(p.Increment),
// 			ui.Textf("clicked %d times", p.Count),
// 		),
// 	)
// }
//
// func (p *IndexPage) Increment() { p.Count++ }
`

const tmplGowaveJS = `/**
 * gowave.js — WASM bootstrap bridge
 * Generated by gowave new. Do not edit — regenerate with gowave new or gowave build.
 */
document.addEventListener('DOMContentLoaded', async () => {
  const GoConstructor = globalThis.Go;
  if (typeof GoConstructor !== 'function') {
    console.warn('[gowave] wasm_exec.js did not define globalThis.Go — check that /wasm_exec.js loaded.');
    return;
  }

  const go = new GoConstructor();
  try {
    const result = await WebAssembly.instantiateStreaming(
      fetch('/_wasm/main.wasm'), go.importObject
    );
    go.run(result.instance);
  } catch (e) {
    console.warn('[gowave] WASM load skipped:', e.message);
  }

  globalThis.__gowave_patch = (patchJSON) => {
    const patches = JSON.parse(patchJSON);
    for (const op of patches) {
      if (op.type === 'full_render') {
        document.getElementById('app-root').innerHTML = op.html;
        return;
      }
      const el = document.querySelector('[data-gw-id="' + op.id + '"]');
      if (!el) continue;
      if (op.type === 'set_text') el.textContent = op.value;
      if (op.type === 'set_attr')  el.setAttribute(op.key, op.value);
      if (op.type === 'replace')   el.outerHTML = op.html;
    }
  };

  document.addEventListener('click', (e) => {
    const id = e.target.dataset?.gwClick;
    if (id && globalThis.__gowave_dispatch) {
      e.preventDefault();
      globalThis.__gowave_dispatch('click', id, '');
    }
  });
  document.addEventListener('input', (e) => {
    const id = e.target.dataset?.gwInput;
    if (id && globalThis.__gowave_dispatch)
      globalThis.__gowave_dispatch('input', id, e.target.value);
  });
  document.addEventListener('keydown', (e) => {
    if (e.key !== 'Enter') return;
    const id = e.target.dataset?.gwEnter;
    if (id && globalThis.__gowave_dispatch)
      globalThis.__gowave_dispatch('enter', id, e.target.value);
  });
});
`
const tmplGitignore = `dist/
*.wasm
*.test
vendor/
.DS_Store
`

const tmplReadme = `# {{.Name}}

Built with [GoWave](https://github.com/gowave/gowave) — Go + WebAssembly, no JS tax.

## Commands

` + "```" + `bash
gowave dev        # start dev server with hot reload → http://localhost:3000
gowave build      # compile to WASM + SSR bundle → dist/
` + "```" + `

## Structure

` + "```" + `
{{.Name}}/
  pages/          # file-based routes  (pages/index.go → /)
  components/     # shared UI components
  store/          # global shared state
  db/             # database layer (server-only)
  middleware/     # HTTP middleware
  public/         # static assets
  layout.go       # root HTML shell
  main.go         # server entrypoint
  gowave.toml     # project config
` + "```"
